name: exam_ai
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  file_picker: ^8.1.2
  flutter_dotenv: ^5.1.0
  flutter_pdfview: ^1.3.3
  docx_to_text: ^1.0.1
  google_sign_in_web: ^0.12.4+2
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.3
  xml: ^6.5.0
  syncfusion_flutter_pdf: ^27.1.52
  google_generative_ai: ^0.4.6

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - .env
    - assets/